openapi: 3.0.2
info:
  title: WNTR EPANET Simulation API
  description: Simulates EPANET models and returns pressure summaries and plots.
  version: "1.0.0"
paths:
  /simulate:
    post:
      summary: Run simulation on .inp file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                inp_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  summary:
                    type: object
                  pressure_plot_base64:
                    type: string