openapi: 3.0.2
info:
  title: WNTR EPANET Simulation API
  description: Simulate EPANET water networks using WNTR and return pressure summaries and plots.
  version: "1.1.0"
servers:
  - url: https://wntr-chatgpt.onrender.com

paths:
  /simulate:
    post:
      summary: Run EPANET simulation
      operationId: simulate_epanet
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                inp_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Simulation results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  summary:
                    type: object
                  markdown:
                    type: string
                  html_chart:
                    type: string
