openapi: 3.0.2
info:
  title: WNTR EPANET Simulation API
  version: "1.1.0"
  description: Simulates an EPANET input file and returns hydraulic results.

servers:
  - url: https://wntr-chatgpt.onrender.com

paths:
  /simulate:
    post:
      operationId: simulate_epanet
      summary: Simulate WNTR model using uploaded EPANET .inp file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - inp_file
              properties:
                inp_file:
                  type: string
                  format: binary
                  description: Upload a valid EPANET .inp file
      responses:
        "200":
          description: Simulation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  summary:
                    type: object
                  markdown:
                    type: string
                  html_chart:
                    type: string
